version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  apache:
    image: httpd:latest
    volumes:
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./src:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --loglevel verbose
    container_name: redis
    restart: always
    volumes:
      - //projects/spring-data-redis-example/src/main/resources/docker/redis/storage:/opt/redis/data/bases
      - //projects/spring-data-redis-example/src/main/resources/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - //projects/spring-data-redis-example/src/main/resources/docker/redis/log/redis-server.log:/opt/redis/logs/redis-server.log
    networks:
      - app-network
    ports:
      - 6379:6379

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: redis-admin
    depends_on:
      - redis
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: admin
      REDIS_1_HOST: 192.168.99.100
      REDIS_1_PORT: 6379
    links:
      - redis
    ports:
      - "8085:80"
    command: --loglevel verbose

  
  memcached:
    image: memcached:latest
    networks:
      - app-network
    ports:
      - "11211:11211"

  memcached-admin:
    image: hatamiarash7/memcached-admin:latest
    environment:
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    ports:
      - "8086:80"

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  # laravel:
  #   build:
  #     context: ./src
  #   volumes:
  #     - ./src:/var/www
  #     - /var/www/vendor
  #     - /var/www/node_modules
  #   networks:
  #     - app-network
  #   environment:
  #     - DB_CONNECTION=mysql
  #     - DB_HOST=mariadb
  #     - DB_PORT=3306
  #     - DB_DATABASE=${MYSQL_DATABASE}
  #     - DB_USERNAME=${MYSQL_USER}
  #     - DB_PASSWORD=${MYSQL_PASSWORD}
  #   depends_on:
  #     - mariadb

  # node:
  #   build:
  #     context: ./node
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./node/src:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     NODE_ENV: development
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

    

volumes:
  db_data:
