version: '3.8'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www/html'
    environment:
      - WWWUSER=${WWWUSER:-1000}
      - WWWGROUP=${WWWGROUP:-1000}
      - LARAVEL_SAIL=1
      - XDEBUG_MODE=${SAIL_XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
    depends_on:
      - mysql
      - redis
      - memcached
      - phpmyadmin
    networks:
      - sail

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '9001:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - sail

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail

  memcached:
    image: 'memcached:alpine'
    ports:
      - '11211:11211'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
